### ISSUE TITLE
💡 Use SystemMouseCursors.click in _SitebarItem so the cursor is correct when hovering the SitebarItems

### ISSUE THREAD

**Issue by mark-nicepants** [macosui/macos_ui#181]
## Use case

When adding a SiteBar like in the example, we don't get a .click mouse indicator. But just the basic. Currently this is not easily modifiable because you cannot wrap the SiteBarItems (the SiteBar expects SitebarItems as children).

## Proposal

Change the mouseCursor to SystemMouseCursors.click in site_bar.dart (line 277).

or alternatively

Expose the mouseCursor property

**Comment by GroovinChip** [comment]
Hi @mark-apn, thanks for asking about this. Can you provide examples of macOS applications (preferably first party Apple applications) that use that kind of mouse cursor in their sidebars? My research indicated that Apple does not use it, which is why I use the generic mouse cursor for sidebar items.

**Comment by mark-nicepants** [comment]
I understand where you're getting at, and I can respect that you want to stay as true to the native experience as you can get. And on that note I guess your right to not implement the `click` cursor as a default. I see that the App store doesn't use the click cursor anywhere, which is a shame in my opinion. 

Would be awesome if we could at least expose the cursor property so that it can be overridden :-)

**Comment by GroovinChip** [comment]
I'll think about it. It's not an unreasonable request.
