### ISSUE TITLE
Breaks with Flutter 3.11

### ISSUE THREAD

**Issue by fennelhans** [macosui/macos_ui#423]
**Description**

```
../../../../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:108:35: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
 - 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../../../bin/flutter/packages/flutter/lib/src/gestures/tap.dart').
 - 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../../bin/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragUpDetails', or, for a covariant parameter, a subtype.
  void onSingleTapUp(TapUpDetails details) {
                                  ^
../../../../../bin/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2198:8: Context: This is the overridden method ('onSingleTapUp').
  void onSingleTapUp(TapDragUpDetails details) {
       ^
../../../../../.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart:130:42: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onDragSelectionEnd' has type 'DragEndDetails', which does not match the corresponding type, 'TapDragEndDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onDragSelectionEnd'.
 - 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../../../bin/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
 - 'TapDragEndDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../../bin/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragEndDetails', or, for a covariant parameter, a subtype.
  void onDragSelectionEnd(DragEndDetails details) {
                                         ^
../../../../../bin/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2886:8: Context: This is the overridden method ('onDragSelectionEnd').
  void onDragSelectionEnd(TapDragEndDetails details) {
       ^
Target kernel_snapshot failed: Exception


FAILURE: Build completed with 2 failures.
```

**Steps To Reproduce**

1. `flutter channel main; flutter upgrade` or wait until tomorrow for the Flutter team to push it to everybody

```
Flutter 3.11.0-2.0.pre.81 • channel main • https://github.com/flutter/flutter.git
Framework • revision a153d6da84 (2 hours ago) • 2023-05-09 14:21:52 -0500
Engine • revision 824cd09b8c
Tools • Dart 3.1.0 (build 3.1.0-87.0.dev) • DevTools 2.23.1
```

**Comment by edeuss** [comment]
@fennelhans Also affects the flutter stable channel v3.10.0

```
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1555], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\Users\Elias\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (28 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
```

**Comment by fennelhans** [comment]
Yes, it does.

**Comment by armandojimenez** [comment]
any plans to update this soon? or is there any way to use the adaptive_dialog with this issue?

**Comment by GroovinChip** [comment]
Sorry folks, I'm just really overwhelmed with life right now. I'm going to try and get to the Dart 3 stuff, but I can't really give a timeline.

**Comment by mono0926** [comment]
#422 seems to fix this issue 👀 
([EDIT] #426 was merged.)

**Comment by mariopepe** [comment]
@GroovinChip it is totally fine, and I wish you all the best in your personal life. We will switch to some custom fork in the meanwhile as it always happens in the flutter ecosystem, it's fine.

But to be fair, this issue was brought to your attention on February the 18th, in other terms, **3 months ago**.

In this issue: https://github.com/macosui/macos_ui/issues/361 , which you closed and replied:
> Eventually the changes causing this issue will come to stable and macos_ui will account for them once they do.

Would you agree on saying that you made a bad call back then?
3 months passed by, maybe back in the past it would have been less stressful for you, you could have worked on it over a longer period of time, don't you think?
Also, don't you think that one of the main purpose of betas is giving devs the chance to test their software so that when a beta become stable, potential issues are already addressed, hence acting as an issue in beta is not an issue at all, is not a forward-looking approach?

Best!

**Comment by GroovinChip** [comment]
Yeah, the thing is, I've been pretty constantly overwhelmed since that time. On February 15th I was laid off from my dream job, and I was heartbroken (and still am, really) and focused on finding another. Initially I thought I could work on macos_ui a lot more freely, but I was wrong. It took two months for that me to find another job, and during all that time I was very  depressed, distressed and overwhelmed. I've now been employed for about a month, and am no longer salaried - I'm hourly, and so I must work longer hours. My personal life is generally overwhelming as well, since I am a  husband, father, dog owner, homeowner, and responsible for many things that come with all that. Not to mention I have many hobbies, and not enough time for them all, and in order to stay sane, literally, I need to engage with some of those hobbies regularly as they give me some relief from all of my stress and responsibilities. Oh, and hey, my grandfather passed away recently, and that came with a humongous pile of complicated things that needed balancing. There's also a ton more personal things I'm dealing with that I'm not going to mention. And as if all of that isn't enough, there's still more! I have ADHD! Which makes literally existing in minimum possible terms a humongous, painful, and exhausting daily chore!

I am **acutely** aware of my responsibility to the community. I really, _really_ am. Flutter fundamentally changed my life for the better, and much of that has been the way our wonderful community has embraced me. Creating and shepherding this project forward is a tremendous honor and privilege, and I'm very grateful for support and recognition it has received. It is very dear to me, and every moment that I'm unable to work on it because of everything I talked about before is distressing. But I can't do everything. Right now, and for several months going, I've been really overwhelmed and dealing with a lot of stuff on top of all the regular things I deal with, personally and professionally, and so while I appreciate your kind words regarding my well-being, I very much do _not_ appreciate your criticism of my handling of this project during an exceptionally difficult period of my life. _I am doing the best that I can_. Unfortunately, right now, my best isn't very much. It won't always be that way, and I can't say when things will start looking up, but eventually they will. You're very fortunate that this is a free and open-source project, because I have poured _literal_ blood, sweat, and tears, into it, and spent _many_ hours of my very busy and complex life doing so.

Thank you again for your kind wishes for my well-being, and I apologize again for the delays my situation is causing.

**Comment by fennelhans** [comment]
@mariopepe Please be kind; your comment was abrasive and unhelpful. This is a free, community-driven project. Nobody "owes" anybody anything, and nothing is stopping you from forking the project.

@GroovinChip I'm sorry you're going through these things. I have, recently, been in a similar situation - as a single father and homeowner, losing my job, struggling with many other things which I won't go into here - and also somebody afflicted with ADHD. Believe me when I say: _I hear you_. I'm particularly sad to hear about your grandfather passing. I hope it was peaceful and he was surrounded by those he loves. My condolences for your loss.

We all very much appreciate the hard work you've put into this project. Perhaps you've got a wishlist of things you'd like to accomplish here that you can post in the project's README so other contributors can help out?

If you're looking for a community of Flutter devs who just like to be around other Flutter devs, reach out to me and I'll get you connected. Stay strong.

**Comment by Adrian-Samoticha** [comment]
@GroovinChip Wow, I wasn’t aware of what you were going through. I noticed that our communication abruptly cut off, and assumed you were “just busy,” so to speak ¹. I had just started a new semester at my university and between my studies and other personal matters I also found myself too overwhelmed and mentally drained to dedicate much time to open-source development — life comes first, after all.

I don’t think I have ADHD, but being an Aspie I think there’s a significant overlap between the way we experience obligations, and I can very much relate to being overwhelmed when multiple responsibilities demand our attention at the same time.

I cannot offer much more than kind words, but I really hope we’ll soon get to a point where we can continue working with each other. Cheers. :)

---

¹For reference to other people reading this: We were currently working on a rather big update that was supposed to provide major improvements regarding color accuracy, and so far we are nowhere done, yet.

**Comment by Ansh-Rathod** [comment]
@GroovinChip I hope you are doing well now!

**Comment by GroovinChip** [comment]
> @GroovinChip I hope you are doing well now! 
> 
>  

Still super overwhelmed, and also with terrible seasonal allergies to boot. Thank you 💙

**Comment by kjxbyz** [comment]
When will the new version be released to `pub.dev`?

**Comment by GroovinChip** [comment]
> When will the new version be released to `pub.dev`?

I don't know when, but my plan is to release a beta to pub, rather than a regular release, given that the current version in dev is a beta.

**Comment by ch13mob** [comment]
Hi, any updates?

**Comment by kw214** [comment]
When will the beta version be released?

**Comment by kjxbyz** [comment]
When will the beta version be released?

**Comment by ch-muhammad-adil** [comment]
any progress at this issue i am facing problem after upgrading to flutter 3.10.x

**Comment by GroovinChip** [comment]
Folks, the first beta of version 2 is now available on pub. Please try it out and let me know if this resolves your issues.

https://pub.dev/packages/macos_ui/versions/2.0.0-beta.1

**Comment by yamsergey** [comment]
> 2.0.0-beta.1

Forks fine for me 👍

**Comment by macwilko** [comment]
Great work on the beta release.

**Comment by bluegene37** [comment]
Cool! Thank you! Appreciated this much.
