### ISSUE TITLE
Theme change doesn't correctly adapt to system 

### ISSUE THREAD

**Issue by macwilko** [macosui/macos_ui#473]
macos_ui widgets don't appear to be able to respond to my theme change event.

I must be doing something wrong, but I can't figure out what it is.

Any help would be appreciated.

https://github.com/macosui/macos_ui/assets/19474610/b0c1f56f-52bc-40ce-9e4f-b17f87d45f3f

<img width="784" alt="Xnapper-2023-08-10-22 24 38" src="https://github.com/macosui/macos_ui/assets/19474610/08216040-5825-4e94-8d2b-5392b292bb39">

**Comment by JH081790** [comment]
I am also seeing this issue, any fix?

**Comment by Adrian-Samoticha** [comment]
If I understand correctly, you’re referring to the “Cancel” button remaining dark after the theme change? Does the issue persist when you install the macos_ui package from the GitHub repository, rather than from pub.dev? ([The push button specifically has been updated quite drastically since 2.0.0 was released.](https://github.com/macosui/macos_ui/pull/471))

**Comment by GroovinChip** [comment]
@mattsrobot are you still encountering this issue?

**Comment by macwilko** [comment]
> @mattsrobot are you still encountering this issue?

I do, but my app probably isn't a fair example. 

I've not yet moved over to MacosWindow and MacosScaffold, which I suspect could cause the problem? I intend to upgrade the desktop app to use those when I get more time to do this. Maybe that'll fix it.

**Comment by GroovinChip** [comment]
Not utilizing those widgets would indeed cause some issues, so I highly recommend doing so.

Given that information, I'm going to close this issue. If it persists after you migrate fully to macos_ui, please reopen. 

Cheers!
